services:
  - type: web
    name: n8n-docker
    env: docker
    plan: free
    autoDeploy: true
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "sourav"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "shiva"
